/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLKS.view;

import QLKS.controller.bophanDao;
import QLKS.model.bophan;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zzgia
 */
public class bophanview extends javax.swing.JFrame {

    /**
     * Creates new form bophan
     */
    private Staffview st = new Staffview();
    public bophanview() {
        initComponents();
//        setBackground(new Color(0,0,0,0));
    }
    public bophanview(Staffview st) {
        initComponents();
        this.st=st;
        btnS.setEnabled(false);
        
    }
    public bophanview(Staffview st,bophan bp) {
        initComponents();
        this.st=st;
        txtbp.setText(bp.getMaBP()); 
        txtbp.setEnabled(false);
        txtTenbp.setText(bp.getTenBP())  ;
        btnT.setEnabled(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbp = new javax.swing.JTextField();
        btnT = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        txtTenbp = new javax.swing.JTextField();
        lblerro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã bộ phân:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên bộ phận:");

        txtbp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnT.setBackground(new java.awt.Color(255, 255, 255));
        btnT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnT.setText("Thêm");
        btnT.setBorder(null);
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        btnS.setBackground(new java.awt.Color(255, 255, 255));
        btnS.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnS.setText("Sửa");
        btnS.setBorder(null);
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        btnQ.setBackground(new java.awt.Color(255, 255, 255));
        btnQ.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnQ.setText("Quay lại");
        btnQ.setBorder(null);
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });

        txtTenbp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblerro.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblerro.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblerro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtbp)
                            .addComponent(txtTenbp))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenbp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblerro)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        if (txtbp.getText().equals("")) {
            lblerro.setText("Hãy điền mã bộ phận");
        } else if(checkMa(txtbp.getText())==true){
            lblerro.setText("Mã bộ phận bị trùng");
        } else if(txtTenbp.getText().equals("")){
            lblerro.setText("Hãy điền tên bộ phận");
        }else {
            int result = JOptionPane.showConfirmDialog(frame,"Bạn có chắc muốn thêm mới bộ phận này không?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                bp.setMaBP(txtbp.getText());
                bp.setTenBP(txtTenbp.getText());
                bpd.insert(bp);
                reset();
                JOptionPane.showMessageDialog(frame,"Thêm mới một bộ phận thành công!","Thêm mới bộ phận.",JOptionPane.INFORMATION_MESSAGE);
                lblerro.setText("");
                this.dispose();
                st.dispose();
                new Staffview().setVisible(true);
            }

        }
    }//GEN-LAST:event_btnTActionPerformed
    
    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        if (txtbp.getText().equals("")) {
            lblerro.setText("Hãy điền mã bộ phận");
        }else if(checkMa(txtbp.getText())!=true){
            lblerro.setText("Mã bộ phận không tồn tại");
        }else if(txtTenbp.getText().equals("")){
            lblerro.setText("Hãy điền tên bộ phận");
        }else {
            int result = JOptionPane.showConfirmDialog(frame,"Bạn có chắc muốn sửa bộ phận này không?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(result == JOptionPane.YES_OPTION)
            {
                bp.setMaBP(txtbp.getText());
                bp.setTenBP(txtTenbp.getText());
                int a= bpd.update(bp);
                if (a==1) {
                    JOptionPane.showMessageDialog(frame,"Sửa bộ phận thành công!","Sửa bộ phận.",JOptionPane.INFORMATION_MESSAGE);
                    lblerro.setText("");
                    this.dispose();
                    Staffview stv = new Staffview();
                    this.dispose();
                    st.dispose();
                    new Staffview().setVisible(true);
                }else
                    JOptionPane.showMessageDialog(frame,"Sửa bộ phận thất bại!","Sửa bộ phận.",JOptionPane.INFORMATION_MESSAGE);
                
            }

        }
    }//GEN-LAST:event_btnSActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bophanview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bophanview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bophanview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bophanview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bophanview().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblerro;
    private javax.swing.JTextField txtTenbp;
    private javax.swing.JTextField txtbp;
    // End of variables declaration//GEN-END:variables
    JFrame frame = new JFrame();
    bophanDao bpd = new bophanDao();
    bophan bp = new bophan();
    List<bophan> list = new ArrayList<>();
    private Boolean checkMa(String ma){
        list=bpd.getAll();
        for (bophan b : list) {
            if(ma.equals(b.getMaBP())){
                return true;
            }
        }
        return false;
    }
    private void reset(){
        txtbp.setText("");
        txtTenbp.setText("");
        
    }
}
