/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLKS.Home;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import QLKS.Login.login;
import static QLKS.Login.login.h;
import QLKS.UI.DatPhong;
import QLKS.UI.QLLP;
import QLKS.UI.QLNK;
import QLKS.UI.ThongTinPhong;
import QLKS.UI.ThuePhong;
import QLKS.UI.TraPhong;
import QLKS.UI.TrangChuDichVu;
import QLKS.controller.userDao;
import QLKS.util.PropertiesNVNow;
import QLKS.view.ChiTietHoaDon;
import QLKS.view.Customview;
import QLKS.view.Staffview;
import QLKS.view.TaiKhoanview;
import QLKS.view.frPhuThu;
import QLKS.view.frSanPham;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author zzgia
 */
public class pnLeft extends javax.swing.JPanel {

    /**
     * Creates new form pnLeft
     */
    public pnLeft() {
        initComponents();
        setOpaque(false);
        HideMenu();
    }
    
    
    public void PQ(){
        PropertiesNVNow pr = new PropertiesNVNow();
        List<String> l = pr.getRemember();
        lblCV.setText(l.get(1));
        lblTenNV.setText(l.get(2));
        
        String ma =  new PropertiesNVNow().getRemember().get(0);
        int st = new userDao().PQ(ma);
        if(st==1){
        //Amin
        btnTK.setVisible(true);
        btnQLTK.setVisible(true);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(true);
        btnQLNV.setVisible(true);
        btnQLLP.setVisible(true);
        btnQLP.setVisible(true);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(true);
        
        btnSP.setVisible(true);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(true);
        btnQLNK.setVisible(true);
        
        btnP.setVisible(true);
        btnDP.setVisible(true);
        btnTP.setVisible(true);
        btnTraPhong.setVisible(true);
                
        }else if(st==2){
        //quan ly
        btnTK.setVisible(true);
        btnQLTK.setVisible(false);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(false);
        btnQLNV.setVisible(false);
        btnQLLP.setVisible(true);
        btnQLP.setVisible(false);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(false);
        
        btnSP.setVisible(true);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(false);
        btnQLNK.setVisible(true);
        
        btnP.setVisible(false);
        btnDP.setVisible(true);
        btnTP.setVisible(true);
        btnTraPhong.setVisible(true);
                
        }else if(st==3){
        //nhân viên
        btnTK.setVisible(true);
        btnQLTK.setVisible(false);
        btnDangXuat.setVisible(true);
        
        btnQL.setVisible(true);
        btnQLKH.setVisible(true);
        btnQLNV.setVisible(false);
        btnQLLP.setVisible(false);
        btnQLP.setVisible(true);
        
        btnDV.setVisible(true);
        
        btnHD.setVisible(false);
        
        btnSP.setVisible(false);
        btnQLPT.setVisible(true);
        btnQLSP.setVisible(false);
        btnQLNK.setVisible(true);
        
        btnP.setVisible(true);
        btnDP.setVisible(true);
        btnTP.setVisible(true);
        btnTraPhong.setVisible(true);
                
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnTK = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JLabel();
        btnQLTK = new javax.swing.JLabel();
        btnQL = new javax.swing.JLabel();
        btnTK = new javax.swing.JLabel();
        pnQL = new javax.swing.JPanel();
        btnQLKH = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JLabel();
        btnQLP = new javax.swing.JLabel();
        btnQLLP = new javax.swing.JLabel();
        pnP = new javax.swing.JPanel();
        btnTraPhong = new javax.swing.JLabel();
        btnTP = new javax.swing.JLabel();
        btnDP = new javax.swing.JLabel();
        btnTT = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnDV = new javax.swing.JLabel();
        btnP = new javax.swing.JLabel();
        btnHD = new javax.swing.JLabel();
        btnSP = new javax.swing.JLabel();
        pnSP = new javax.swing.JPanel();
        btnQLPT = new javax.swing.JLabel();
        btnQLSP = new javax.swing.JLabel();
        btnQLNK = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MIA HOTEL");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hotels & Spa");

        lblCV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCV.setForeground(new java.awt.Color(255, 255, 255));

        lblTenNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblCV, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jPanel4.setOpaque(false);

        pnTK.setOpaque(false);

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("            Đăng xuất");
        btnDangXuat.setMaximumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(150, 28));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(150, 28));
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        btnQLTK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLTK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTK.setText("            Quản lý tài khoản");
        btnQLTK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLTK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLTKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnTKLayout = new javax.swing.GroupLayout(pnTK);
        pnTK.setLayout(pnTKLayout);
        pnTKLayout.setHorizontalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLTK, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTKLayout.setVerticalGroup(
            pnTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTKLayout.createSequentialGroup()
                .addComponent(btnQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnQL.setBackground(new java.awt.Color(255, 255, 255));
        btnQL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQL.setForeground(new java.awt.Color(255, 255, 255));
        btnQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager.png"))); // NOI18N
        btnQL.setText("Quản Lý");
        btnQL.setIconTextGap(15);
        btnQL.setMaximumSize(new java.awt.Dimension(172, 48));
        btnQL.setMinimumSize(new java.awt.Dimension(172, 48));
        btnQL.setPreferredSize(new java.awt.Dimension(172, 48));
        btnQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLMouseClicked(evt);
            }
        });

        btnTK.setBackground(new java.awt.Color(255, 255, 255));
        btnTK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTK.setForeground(new java.awt.Color(255, 255, 255));
        btnTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnTK.setText("Tài Khoản");
        btnTK.setIconTextGap(15);
        btnTK.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTK.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTK.setName(""); // NOI18N
        btnTK.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKMouseClicked(evt);
            }
        });

        pnQL.setOpaque(false);

        btnQLKH.setBackground(new java.awt.Color(255, 255, 255));
        btnQLKH.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLKH.setForeground(new java.awt.Color(255, 255, 255));
        btnQLKH.setText("            Quản lý khách hàng");
        btnQLKH.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLKH.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLKH.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLKHMouseClicked(evt);
            }
        });

        btnQLNV.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLNV.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNV.setText("            Quản lý nhân viên");
        btnQLNV.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLNV.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNVMouseClicked(evt);
            }
        });

        btnQLP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLP.setText("            Quản lý phòng");
        btnQLP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPMouseClicked(evt);
            }
        });

        btnQLLP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLLP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLLP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLLP.setText("            Quản lý loại phòng");
        btnQLLP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLLP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLLP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLLPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnQLLayout = new javax.swing.GroupLayout(pnQL);
        pnQL.setLayout(pnQLLayout);
        pnQLLayout.setHorizontalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLLayout.setVerticalGroup(
            pnQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLLayout.createSequentialGroup()
                .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLLP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnP.setOpaque(false);

        btnTraPhong.setBackground(new java.awt.Color(255, 255, 255));
        btnTraPhong.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTraPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnTraPhong.setText("            Trả phòng");
        btnTraPhong.setMaximumSize(new java.awt.Dimension(150, 28));
        btnTraPhong.setMinimumSize(new java.awt.Dimension(150, 28));
        btnTraPhong.setPreferredSize(new java.awt.Dimension(150, 28));
        btnTraPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraPhongMouseClicked(evt);
            }
        });

        btnTP.setBackground(new java.awt.Color(255, 255, 255));
        btnTP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTP.setForeground(new java.awt.Color(255, 255, 255));
        btnTP.setText("            Thuê Phòng");
        btnTP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnTP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnTP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTPMouseClicked(evt);
            }
        });

        btnDP.setBackground(new java.awt.Color(255, 255, 255));
        btnDP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDP.setForeground(new java.awt.Color(255, 255, 255));
        btnDP.setText("            Đặt phòng");
        btnDP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnDP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnDP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnPLayout = new javax.swing.GroupLayout(pnP);
        pnP.setLayout(pnPLayout);
        pnPLayout.setHorizontalGroup(
            pnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTraPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnPLayout.setVerticalGroup(
            pnPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPLayout.createSequentialGroup()
                .addComponent(btnDP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnTT.setBackground(new java.awt.Color(255, 255, 255));
        btnTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTT.setForeground(new java.awt.Color(255, 255, 255));
        btnTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thông tin.png"))); // NOI18N
        btnTT.setText("Thông Tin");
        btnTT.setIconTextGap(15);
        btnTT.setMaximumSize(new java.awt.Dimension(172, 48));
        btnTT.setMinimumSize(new java.awt.Dimension(172, 48));
        btnTT.setPreferredSize(new java.awt.Dimension(172, 48));
        btnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTTMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.setDisabledIcon(null);
        btnExit.setFocusable(false);
        btnExit.setIconTextGap(15);
        btnExit.setMaximumSize(new java.awt.Dimension(172, 48));
        btnExit.setMinimumSize(new java.awt.Dimension(172, 48));
        btnExit.setPreferredSize(new java.awt.Dimension(172, 48));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnExitKeyTyped(evt);
            }
        });

        btnDV.setBackground(new java.awt.Color(255, 255, 255));
        btnDV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDV.setForeground(new java.awt.Color(255, 255, 255));
        btnDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dịch vụ.png"))); // NOI18N
        btnDV.setText("Dịch vụ");
        btnDV.setIconTextGap(15);
        btnDV.setMaximumSize(new java.awt.Dimension(172, 48));
        btnDV.setMinimumSize(new java.awt.Dimension(172, 48));
        btnDV.setPreferredSize(new java.awt.Dimension(172, 48));
        btnDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDVMouseClicked(evt);
            }
        });

        btnP.setBackground(new java.awt.Color(255, 255, 255));
        btnP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnP.setForeground(new java.awt.Color(255, 255, 255));
        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnP.setText("Phòng");
        btnP.setIconTextGap(15);
        btnP.setMaximumSize(new java.awt.Dimension(172, 48));
        btnP.setMinimumSize(new java.awt.Dimension(172, 48));
        btnP.setPreferredSize(new java.awt.Dimension(172, 48));
        btnP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPMouseClicked(evt);
            }
        });

        btnHD.setBackground(new java.awt.Color(255, 255, 255));
        btnHD.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnHD.setForeground(new java.awt.Color(255, 255, 255));
        btnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hóa đơn.png"))); // NOI18N
        btnHD.setText("Chi tiết hóa đơn");
        btnHD.setIconTextGap(15);
        btnHD.setMaximumSize(new java.awt.Dimension(172, 48));
        btnHD.setMinimumSize(new java.awt.Dimension(172, 48));
        btnHD.setPreferredSize(new java.awt.Dimension(172, 48));
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHDMouseClicked(evt);
            }
        });

        btnSP.setBackground(new java.awt.Color(255, 255, 255));
        btnSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSP.setForeground(new java.awt.Color(255, 255, 255));
        btnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sản phẩm.png"))); // NOI18N
        btnSP.setText("Sản phẩm");
        btnSP.setIconTextGap(15);
        btnSP.setMaximumSize(new java.awt.Dimension(172, 48));
        btnSP.setMinimumSize(new java.awt.Dimension(172, 48));
        btnSP.setPreferredSize(new java.awt.Dimension(172, 48));
        btnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSPMouseClicked(evt);
            }
        });

        pnSP.setOpaque(false);

        btnQLPT.setBackground(new java.awt.Color(255, 255, 255));
        btnQLPT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLPT.setForeground(new java.awt.Color(255, 255, 255));
        btnQLPT.setText("            Quản lý phụ thu");
        btnQLPT.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLPT.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPTMouseClicked(evt);
            }
        });

        btnQLSP.setBackground(new java.awt.Color(255, 255, 255));
        btnQLSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLSP.setForeground(new java.awt.Color(255, 255, 255));
        btnQLSP.setText("            Quản lý sản phẩm");
        btnQLSP.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLSP.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSPMouseClicked(evt);
            }
        });

        btnQLNK.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNK.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnQLNK.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNK.setText("            Quản lý nhập kho");
        btnQLNK.setMaximumSize(new java.awt.Dimension(150, 28));
        btnQLNK.setMinimumSize(new java.awt.Dimension(150, 28));
        btnQLNK.setPreferredSize(new java.awt.Dimension(150, 28));
        btnQLNK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnSPLayout = new javax.swing.GroupLayout(pnSP);
        pnSP.setLayout(pnSPLayout);
        pnSPLayout.setHorizontalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQLPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnSPLayout.setVerticalGroup(
            pnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSPLayout.createSequentialGroup()
                .addComponent(btnQLPT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQLNK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQL, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addComponent(pnQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKMouseClicked
        
        boolean a = pnTK.isVisible();
        HideMenu();
        if (a==true) {
            pnTK.setVisible(false);
        } else {
            pnTK.setVisible(true);
        }
        
    }//GEN-LAST:event_btnTKMouseClicked

    private void btnQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLMouseClicked
        boolean a = pnQL.isVisible();
        HideMenu();
        if (a==true) {
            pnQL.setVisible(false);
        } else {
            pnQL.setVisible(true);
        }
    }//GEN-LAST:event_btnQLMouseClicked

    private void btnPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPMouseClicked
        boolean a = pnP.isVisible();
        HideMenu();
        if (a==true) {
            pnP.setVisible(false);
        } else {
            pnP.setVisible(true);
        }
    }//GEN-LAST:event_btnPMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        HideMenu();
        h.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDVMouseClicked
        HideMenu();
        h.dispose();
        new TrangChuDichVu().setVisible(true);
    }//GEN-LAST:event_btnDVMouseClicked

    private void btnQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseClicked
        HideMenu();
        h.dispose();
        new Staffview().setVisible(true);
    }//GEN-LAST:event_btnQLNVMouseClicked

    private void btnQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLTKMouseClicked
        HideMenu();
        h.dispose();
        new TaiKhoanview().setVisible(true);
    }//GEN-LAST:event_btnQLTKMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked
        
        HideMenu();
        lblCV.setText("");
        lblTenNV.setText("");
        h.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_btnDangXuatMouseClicked

    private void btnExitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyTyped
        // TODO add your handling code here:
        HideMenu();
        h.dispose();
    }//GEN-LAST:event_btnExitKeyTyped

    private void btnTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTMouseClicked
        HideMenu();
        String tt = "";
            tt += "Phần mềm : Quản lý Khách sạn MIA \n";
            tt += "\n ";
            tt += "version : 1.1";
            tt += "\n\n";
            tt += "_____________Bài tập lớn______________ ";
            tt += "\n\n\n";
            tt += " Trường Đại học Công Nghệ Giao Thông Vận Tải";
            tt += "\n";
            tt += " Lớp: 70DCTT21";
            tt += "\n";
            tt += " Học phần : Lập trình java nâng cao";
            tt += "\n";
            tt += "Nhóm thực hiện: Nhóm 3.";
            tt += "\n\n\nThành viên nhóm: ";
            tt += "\n         - Nhóm trưởng: Nguyễn Quang Bảo. ";
            tt += "\n         - Đội viên:    Phạm Đình Thắng. ";
            tt += "\n         - Đội viên:    Nguyễn Nghĩa Ninh. ";
            tt += "\n         - Đội viên:    Đinh Đức Mạnh. ";
            JOptionPane.showMessageDialog(h,tt,"Thông tin",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTTMouseClicked

    private void btnQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseClicked
        HideMenu();
        h.dispose();
        new Customview().setVisible(true);
    }//GEN-LAST:event_btnQLKHMouseClicked

    private void btnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseClicked
        HideMenu();
        h.dispose();
        try {
            new ChiTietHoaDon().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pnLeft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHDMouseClicked

    private void btnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseClicked
        boolean a = pnSP.isVisible();
        HideMenu();
        if (a==true) {
            pnSP.setVisible(false);
        } else {
            pnSP.setVisible(true);
        }
    }//GEN-LAST:event_btnSPMouseClicked

    private void btnQLPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPTMouseClicked
        HideMenu();
        h.dispose();
        try {
            new frPhuThu().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(pnLeft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLPTMouseClicked

    private void btnQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSPMouseClicked
        HideMenu();
        h.dispose();
        new frSanPham().setVisible(true);
    }//GEN-LAST:event_btnQLSPMouseClicked

    private void btnQLNKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNKMouseClicked
        HideMenu();
        h.dispose();
        new QLNK().setVisible(true);
    }//GEN-LAST:event_btnQLNKMouseClicked

    private void btnQLLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLLPMouseClicked
        HideMenu();
        h.dispose();
        new QLLP().setVisible(true);
    }//GEN-LAST:event_btnQLLPMouseClicked

    private void btnQLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseClicked
        HideMenu();
        h.dispose();
        new ThongTinPhong().setVisible(true);
    }//GEN-LAST:event_btnQLPMouseClicked

    private void btnDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDPMouseClicked
        HideMenu();
        h.dispose();
        new DatPhong().setVisible(true);
    }//GEN-LAST:event_btnDPMouseClicked

    private void btnTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTPMouseClicked
        HideMenu();
        h.dispose();
        new ThuePhong().setVisible(true);
    }//GEN-LAST:event_btnTPMouseClicked

    private void btnTraPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTraPhongMouseClicked
        HideMenu();
        h.dispose();
        new TraPhong().setVisible(true);
    }//GEN-LAST:event_btnTraPhongMouseClicked

     @Override
    protected void paintComponent(Graphics grp){
        Graphics2D g2 =(Graphics2D) grp;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
        
        String colorTop ="#1cb5e0";
        String colorBottom ="#000046";
        
        GradientPaint g = new GradientPaint(0,0,Color.decode(colorTop),0,getHeight(),Color.decode(colorBottom));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintComponent(grp);
        
    }
    

    public void HideMenu()
        {
            PQ();
            pnSP.setVisible(false);
            pnTK.setVisible(false);
            pnQL.setVisible(false);
            pnP.setVisible(false);
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDP;
    private javax.swing.JLabel btnDV;
    private javax.swing.JLabel btnDangXuat;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHD;
    private javax.swing.JLabel btnP;
    private javax.swing.JLabel btnQL;
    private javax.swing.JLabel btnQLKH;
    private javax.swing.JLabel btnQLLP;
    private javax.swing.JLabel btnQLNK;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JLabel btnQLP;
    private javax.swing.JLabel btnQLPT;
    private javax.swing.JLabel btnQLSP;
    private javax.swing.JLabel btnQLTK;
    private javax.swing.JLabel btnSP;
    private javax.swing.JLabel btnTK;
    private javax.swing.JLabel btnTP;
    private javax.swing.JLabel btnTT;
    private javax.swing.JLabel btnTraPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCV;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnP;
    private javax.swing.JPanel pnQL;
    private javax.swing.JPanel pnSP;
    private javax.swing.JPanel pnTK;
    // End of variables declaration//GEN-END:variables
}
